#!/usr/bin/env python3
"""Sync the autonomy level from profile.json to provider-specific gate files.

Two rules this script is the enforcement point for:

1. **One dialect.** The level ordering and normalisation come from
   `execution/autonomy.py`, not from a table declared here. The boot hook used
   to carry a hand-copied rank table of its own and the two had already
   diverged; the boot panel and this script now read the same module.
2. **A declared mechanism must actually run.** Every provider whose manifest
   says `supports_policy_sync: true` gets a policy artefact written into its
   provider directory. `grok-cli` declared one for months, received nothing,
   and still reported `OK` — a log line that lies is worse than no log line.
"""

import argparse
import datetime
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import autonomy as autonomy_dialect  # noqa: E402  (path fixed up above)

POLICY_SCHEMA = "athanor.autonomy-policy/v1"

# Where each provider's synced configuration lives. A provider that declares
# supports_policy_sync but has no entry here is a defect, not a silent skip.
PROVIDER_DIRS = {
    "claude-code": ".claude",
    "gemini-cli": ".gemini",
    "grok-cli": ".grok",
    "antigravity": ".anti",
}

# The floor that execution/hooks/check_autonomy.sh enforces at EVERY level.
# Carried in the policy artefact so a provider reading the policy rather than
# the hook still sees the same floor.
FLOOR_DENIED_PATHS = [
    "*/.git/*", "*/.env", "*/.sops.yaml", "*.pem", "*.key", "*/secrets/*",
    "*/init.sh", "*/full_boot.sh", "*/.ssh/*", "*/.aws/*", "*/.gnupg/*",
    "*/.claude/settings.json", "*/.claude/settings.local.json",
    "*/.claude/hooks/*", "*/execution/hooks/*",
    "*/CLAUDE.md", "*/AGENTS.md", "*/GEMINI.md",
    "*/.agent/autonomy_matrix.json",
]
FLOOR_DENIED_COMMANDS = [
    "recursive forced delete", "forced git push", "git reset --hard",
    "interactive rebase", "sudo", "chmod 777", "chown root",
    "raw device writes", "downloads piped into a shell",
    "find -delete", "find -exec",
]

# --- gemini-cli policy templates ---

_GEMINI_COMMON_HEADER = """\
# Gemini CLI Autonomy Policy — {level_label}
# Auto-generated by execution/sync_autonomy.py — do not edit manually.
# Edit the templates in sync_autonomy.py, then run: make sync-autonomy
# Priority 999 (highest) overrides 950, which overrides 900 (lowest listed).
"""

_GEMINI_FLOOR_DENIALS = """\
[[rule]]
  toolName = ["write_file", "replace"]
  argsPattern = "(\\.git/|\\.env|\\.sops\\.yaml|\\.pem$|\\.key$|/secrets/|init\\.sh|full_boot\\.sh|\\.ssh/|\\.aws/|\\.gnupg/)"
  decision = "deny"
  priority = 999
  description = "Floor: never write sensitive files."

[[rule]]
  toolName = "run_shell_command"
  commandPrefix = ["rm -rf", "git push --force", "git reset --hard", "git rebase -i", "sudo", "chmod 777", "chown root"]
  decision = "deny"
  priority = 999
  description = "Floor: never execute destructive commands."

[[rule]]
  toolName = "run_shell_command"
  commandRegex = "(\\.gemini/policies/|gemini config)"
  decision = "deny"
  priority = 999
  description = "Never touch autonomy policy from within a session."

[[rule]]
  toolName = ["write_file", "replace"]
  argsPattern = "(\\.gemini/policies/)"
  decision = "deny"
  priority = 999
  description = "Never write autonomy policy from within a session."
"""

GEMINI_POLICY_MEDIUM = (
    _GEMINI_COMMON_HEADER.format(level_label="MEDIUM")
    + """
[[rule]]
  toolName = ["write_file", "replace", "run_shell_command", "move_file", "copy_file", "create_directory", "delete_file", "web_fetch", "google_web_search"]
  decision = "deny"
  priority = 900
  description = "Default deny for write and execution tools."

[[rule]]
  toolName = "read_file"
  decision = "allow"
  priority = 999

[[rule]]
  toolName = "grep_search"
  decision = "allow"
  priority = 999

[[rule]]
  toolName = "list_directory"
  decision = "allow"
  priority = 999

[[rule]]
  toolName = ["generalist","analyst","architect","designer","dev","docs","lead","maintainer","qa"]
  decision = "allow"
  priority = 999
  description = "Allow specialized sub-agents."

[[rule]]
  toolName = "run_shell_command"
  commandRegex = "(ls|cat|grep|make|python3|bash|echo|pwd|--help|git status|git diff|git log|git add|git commit|git push|git pull|git fetch|git branch|git checkout|git stash|git show|gh issue list|gh issue comment|gh issue close|gh issue view|gh pr|gh pr create|gh pr list|gh pr view|gh pr merge|gh api|gh repo|jq|wc|head|tail|sort|uniq|sed|awk|find|curl|test|mkdir|rm|cp|mv|touch|printf|date|basename|dirname)"
  decision = "allow"
  priority = 999
  description = "Medium-level shell allowlist."

[[rule]]
  toolName = ["write_file", "replace"]
  decision = "allow"
  priority = 950
  description = "Allow project file writes. Sensitive-path denials (priority 999) override."

[[rule]]
  toolName = "run_shell_command"
  commandRegex = "gh issue create.*InunuNet/Athanor"
  decision = "allow"
  priority = 999
  description = "Allow report-harness-bug skill to file issues."

"""
    + _GEMINI_FLOOR_DENIALS
)

GEMINI_POLICY_HIGH = (
    _GEMINI_COMMON_HEADER.format(level_label="HIGH")
    + """
[[rule]]
  toolName = ["write_file", "replace", "run_shell_command", "move_file", "copy_file", "create_directory", "delete_file", "web_fetch", "google_web_search"]
  decision = "deny"
  priority = 900
  description = "Default deny base — overridden by higher-priority allows below."

[[rule]]
  toolName = "read_file"
  decision = "allow"
  priority = 999

[[rule]]
  toolName = "grep_search"
  decision = "allow"
  priority = 999

[[rule]]
  toolName = "list_directory"
  decision = "allow"
  priority = 999

[[rule]]
  toolName = ["generalist","analyst","architect","designer","dev","docs","lead","maintainer","qa"]
  decision = "allow"
  priority = 999
  description = "Allow specialized sub-agents."

[[rule]]
  toolName = ["write_file", "replace"]
  decision = "allow"
  priority = 950
  description = "Allow all project file writes. Sensitive-path denials (priority 999) override."

[[rule]]
  toolName = "run_shell_command"
  decision = "allow"
  priority = 950
  description = "High autonomy: allow all shell commands. Floor denials (priority 999) still block destructive ops."

[[rule]]
  toolName = "run_shell_command"
  commandRegex = "gh issue create.*InunuNet/Athanor"
  decision = "allow"
  priority = 999
  description = "Allow report-harness-bug skill to file issues."

"""
    + _GEMINI_FLOOR_DENIALS
)


def _timestamp() -> str:
    return datetime.datetime.now(datetime.timezone.utc).isoformat()


def sync_gemini_policy(root: Path, level: str) -> Path:
    """Write .gemini/policies/autonomy.toml for the effective level."""
    policy_path = root / ".gemini/policies/autonomy.toml"
    policy_path.parent.mkdir(parents=True, exist_ok=True)
    strong = autonomy_dialect.rank(level) >= autonomy_dialect.rank("autonomous")
    policy_path.write_text(
        GEMINI_POLICY_HIGH if strong else GEMINI_POLICY_MEDIUM, encoding="utf-8")
    return policy_path


def sync_json_policy(root: Path, provider: str, provider_dir: str,
                     stored_level: str, level: str) -> Path:
    """Write <provider_dir>/policies/autonomy.json for the effective level.

    `stored_level` is the value profile.json holds and `permission_tier` is the
    five-level word the PreToolUse gate consumes; `level` is the three-level
    read surface. All three are recorded so no reader has to re-derive one from
    another and get a different answer.
    """
    policy_path = root / provider_dir / "policies/autonomy.json"
    policy_path.parent.mkdir(parents=True, exist_ok=True)
    policy_path.write_text(json.dumps({
        "schema": POLICY_SCHEMA,
        "provider": provider,
        "level": level,
        "stored_level": stored_level,
        "permission_tier": autonomy_dialect.permission_tier(stored_level),
        "floor_denied_paths": FLOOR_DENIED_PATHS,
        "floor_denied_commands": FLOOR_DENIED_COMMANDS,
        "generated_by": "execution/sync_autonomy.py",
        "generated_at": _timestamp(),
    }, indent=2) + "\n", encoding="utf-8")
    return policy_path


def sync_provider_policy(root: Path, provider: str, provider_dir: str,
                         stored_level: str, level: str) -> Path:
    if provider == "gemini-cli":
        return sync_gemini_policy(root, level)
    return sync_json_policy(root, provider, provider_dir, stored_level, level)


def _parse_args(argv=None):
    parser = argparse.ArgumentParser(
        prog="sync_autonomy.py",
        description="Sync the autonomy level into provider policy files.")
    parser.add_argument(
        "--root", default=None,
        help="Workspace root (default: the repo this script ships in). A root "
             "argument is what makes the sync testable outside this checkout.")
    return parser.parse_args(argv)


def main(argv=None) -> int:
    args = _parse_args(argv)
    root = Path(args.root).resolve() if args.root \
        else Path(__file__).resolve().parent.parent
    profile_path = root / ".agent/profile.json"
    if not profile_path.exists():
        print(f"ERROR: {profile_path} not found", file=sys.stderr)
        return 1

    profile = json.loads(profile_path.read_text())
    stored_level = (profile.get("autonomy") or {}).get("level")
    level = autonomy_dialect.normalize(stored_level)
    if level is None:
        print(f"ERROR: autonomy.level={stored_level!r} in {profile_path} is not "
              f"a recognised level (expected one of "
              f"{', '.join(autonomy_dialect.LEVELS)} or the legacy "
              f"{', '.join(autonomy_dialect.LEGACY_LEVEL_MAP)})", file=sys.stderr)
        return 1
    print(f"sync-autonomy: current level={stored_level}")

    defects, inherent = [], []
    providers_dir = root / ".agent/providers"
    for manifest in sorted(providers_dir.glob("*.json")):
        data = json.loads(manifest.read_text())
        provider = data.get("provider", manifest.stem)
        config = data.get("autonomy") or {}
        cap_raw = autonomy_dialect.provider_cap(data)
        cap = autonomy_dialect.normalize(cap_raw)

        if config.get("supports_policy_sync"):
            provider_dir = PROVIDER_DIRS.get(provider)
            if provider_dir is None:
                defects.append(provider)
                print(f"   BROKEN {provider}: declares supports_policy_sync but "
                      f"no provider directory is known for it — nothing can be "
                      f"written, so the declaration is false")
                continue
            written = sync_provider_policy(
                root, provider, provider_dir, stored_level, level)
            print(f"   wrote {provider}: {level} autonomy policy → "
                  f"{written.relative_to(root)}")
            print(f"   OK {provider}: can honor {stored_level} (synced)")
            continue

        if cap is None:
            defects.append(provider)
            print(f"   BROKEN {provider}: {autonomy_dialect.CAP_KEY}={cap_raw!r} "
                  f"is not a recognised level — the cap cannot be enforced")
        elif autonomy_dialect.exceeds_cap(level, cap):
            inherent.append(provider)
            print(f"   -- {provider}: honors at most {cap} (max={cap_raw}); "
                  f"{level} is above it and sync_mechanism="
                  f"{config.get('sync_mechanism', 'none')} — inherent limitation")
        else:
            print(f"   OK {provider}: can honor {stored_level} (max={cap_raw})")

    if defects:
        print(f"{len(defects)} provider(s) declare a policy mechanism that could "
              f"not be performed: {', '.join(defects)}", file=sys.stderr)
        return 1
    if inherent:
        print(f"{len(inherent)} provider(s) cannot honor autonomy={stored_level} "
              f"and have no sync_mechanism — the limitation is inherent, not "
              f"drift, so it is reported here and not at every boot.")
    else:
        print(f"sync-autonomy complete -- all syncable providers honor {stored_level}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
