import {
  isWasteTypesOtherFieldApplicable,
  type VendorRegisterFieldChangeHandler,
  type VendorRegisterFormState,
} from '@/lib/vendor-register-form-payload';
import { VendorFormField } from './VendorFormField';
import { VendorCheckboxGroupField } from './VendorCheckboxGroupField';

// Lee-Ann's 2026-10-07 source doc (F1, vendor-form-copy-20261007), "WASTE, CLEANING AND
// ENVIROMENTAL IMPACTS" section (source spelling kept) -- entirely missing from the live form
// before this feature.
// wasteTypes/wasteTypesOther wire onto already-validated server fields (lib/vendor-
// submissions.ts's VENDOR_WASTE_TYPES enum, untouched by this feature -- see the golden's
// "Finding that changes the shape of this feature"). The data model's other waste field under
// this heading has no corresponding source text and is deliberately left unrendered -- see the
// golden's "Gaps/questions for Lee-Ann" item 2.
interface VendorWasteFieldsetProps {
  state: VendorRegisterFormState;
  onFieldChange: VendorRegisterFieldChangeHandler;
  disabled: boolean;
}

const WASTE_TYPE_OPTIONS = [
  { value: 'general', label: 'General waste' },
  { value: 'cardboard-packaging', label: 'Cardboard / packaging' },
  { value: 'plant-material', label: 'Plant material' },
  { value: 'food-waste', label: 'Food Waste' },
  { value: 'wastewater', label: 'Wastewater' },
  { value: 'other', label: 'Other' },
];

export function VendorWasteFieldset({ state, onFieldChange, disabled }: VendorWasteFieldsetProps) {
  return (
    <div className="space-y-5">
      <h2 className="font-serif text-[20px] font-semibold text-ink">
        Waste, cleaning and enviromental impacts
      </h2>

      <VendorCheckboxGroupField
        fieldKey="wasteTypes"
        label="Waste generated by your operation"
        options={WASTE_TYPE_OPTIONS}
        value={state.wasteTypes}
        onChange={(v) => onFieldChange('wasteTypes', v)}
        disabled={disabled}
        required={false}
      />
      {isWasteTypesOtherFieldApplicable(state) ? (
        <VendorFormField
          fieldKey="wasteTypesOther"
          label="Other"
          htmlType="text"
          value={state.wasteTypesOther}
          onChange={(v) => onFieldChange('wasteTypesOther', v)}
          disabled={disabled}
          required={false}
          maxLength={100}
        />
      ) : null}

      <p className="font-sans text-[13px] leading-relaxed text-ink/70">
        Vendors are responsible for maintaining a clean and safe booths throughout the event and for complying with the organiser&apos;s waste and recycling procedures.
      </p>
    </div>
  );
}
