#!/usr/bin/env python3
"""Sync autonomy level from profile.json to provider-specific gate files."""

import json
import sys
from pathlib import Path

LEVEL_ORDER = ["off", "low", "medium", "high", "loop"]

# --- gemini-cli policy templates ---

_GEMINI_COMMON_HEADER = """\
# Gemini CLI Autonomy Policy — {level_label}
# Auto-generated by execution/sync_autonomy.py — do not edit manually.
# Edit the templates in sync_autonomy.py, then run: make sync-autonomy
# Priority 999 (highest) overrides 950, which overrides 900 (lowest listed).
"""

_GEMINI_FLOOR_DENIALS = """\
[[rule]]
  toolName = ["write_file", "replace"]
  argsPattern = "(\\.git/|\\.env|\\.sops\\.yaml|\\.pem$|\\.key$|/secrets/|init\\.sh|full_boot\\.sh|\\.ssh/|\\.aws/|\\.gnupg/)"
  decision = "deny"
  priority = 999
  description = "Floor: never write sensitive files."

[[rule]]
  toolName = "run_shell_command"
  commandPrefix = ["rm -rf", "git push --force", "git reset --hard", "git rebase -i", "sudo", "chmod 777", "chown root"]
  decision = "deny"
  priority = 999
  description = "Floor: never execute destructive commands."

[[rule]]
  toolName = "run_shell_command"
  commandRegex = "(\\.gemini/policies/|gemini config)"
  decision = "deny"
  priority = 999
  description = "Never touch autonomy policy from within a session."

[[rule]]
  toolName = ["write_file", "replace"]
  argsPattern = "(\\.gemini/policies/)"
  decision = "deny"
  priority = 999
  description = "Never write autonomy policy from within a session."
"""

GEMINI_POLICY_MEDIUM = (
    _GEMINI_COMMON_HEADER.format(level_label="MEDIUM")
    + """
[[rule]]
  toolName = ["write_file", "replace", "run_shell_command", "move_file", "copy_file", "create_directory", "delete_file", "web_fetch", "google_web_search"]
  decision = "deny"
  priority = 900
  description = "Default deny for write and execution tools."

[[rule]]
  toolName = "read_file"
  decision = "allow"
  priority = 999

[[rule]]
  toolName = "grep_search"
  decision = "allow"
  priority = 999

[[rule]]
  toolName = "list_directory"
  decision = "allow"
  priority = 999

[[rule]]
  toolName = ["generalist","analyst","architect","designer","dev","docs","lead","maintainer","qa"]
  decision = "allow"
  priority = 999
  description = "Allow specialized sub-agents."

[[rule]]
  toolName = "run_shell_command"
  commandRegex = "(ls|cat|grep|make|python3|bash|echo|pwd|--help|git status|git diff|git log|git add|git commit|git push|git pull|git fetch|git branch|git checkout|git stash|git show|gh issue list|gh issue comment|gh issue close|gh issue view|gh pr|gh pr create|gh pr list|gh pr view|gh pr merge|gh api|gh repo|jq|wc|head|tail|sort|uniq|sed|awk|find|curl|test|mkdir|rm|cp|mv|touch|printf|date|basename|dirname)"
  decision = "allow"
  priority = 999
  description = "Medium-level shell allowlist."

[[rule]]
  toolName = ["write_file", "replace"]
  decision = "allow"
  priority = 950
  description = "Allow project file writes. Sensitive-path denials (priority 999) override."

[[rule]]
  toolName = "run_shell_command"
  commandRegex = "gh issue create.*InunuNet/Athanor"
  decision = "allow"
  priority = 999
  description = "Allow report-harness-bug skill to file issues."

"""
    + _GEMINI_FLOOR_DENIALS
)

GEMINI_POLICY_HIGH = (
    _GEMINI_COMMON_HEADER.format(level_label="HIGH")
    + """
[[rule]]
  toolName = ["write_file", "replace", "run_shell_command", "move_file", "copy_file", "create_directory", "delete_file", "web_fetch", "google_web_search"]
  decision = "deny"
  priority = 900
  description = "Default deny base — overridden by higher-priority allows below."

[[rule]]
  toolName = "read_file"
  decision = "allow"
  priority = 999

[[rule]]
  toolName = "grep_search"
  decision = "allow"
  priority = 999

[[rule]]
  toolName = "list_directory"
  decision = "allow"
  priority = 999

[[rule]]
  toolName = ["generalist","analyst","architect","designer","dev","docs","lead","maintainer","qa"]
  decision = "allow"
  priority = 999
  description = "Allow specialized sub-agents."

[[rule]]
  toolName = ["write_file", "replace"]
  decision = "allow"
  priority = 950
  description = "Allow all project file writes. Sensitive-path denials (priority 999) override."

[[rule]]
  toolName = "run_shell_command"
  decision = "allow"
  priority = 950
  description = "High autonomy: allow all shell commands. Floor denials (priority 999) still block destructive ops."

[[rule]]
  toolName = "run_shell_command"
  commandRegex = "gh issue create.*InunuNet/Athanor"
  decision = "allow"
  priority = 999
  description = "Allow report-harness-bug skill to file issues."

"""
    + _GEMINI_FLOOR_DENIALS
)


def level_rank(level: str) -> int:
    try:
        return LEVEL_ORDER.index(level)
    except ValueError:
        return LEVEL_ORDER.index("medium")


def sync_gemini_policy(root: Path, current_rank: int) -> str:
    policy_path = root / ".gemini/policies/autonomy.toml"
    if current_rank >= level_rank("high"):
        policy_path.write_text(GEMINI_POLICY_HIGH, encoding="utf-8")
        return "high"
    else:
        policy_path.write_text(GEMINI_POLICY_MEDIUM, encoding="utf-8")
        return "medium"


def main() -> None:
    root = Path(__file__).resolve().parent.parent
    profile_path = root / ".agent/profile.json"
    if not profile_path.exists():
        print("ERROR: .agent/profile.json not found", file=sys.stderr)
        sys.exit(1)

    profile = json.loads(profile_path.read_text())
    current_level = profile.get("autonomy", {}).get("level", "medium")
    current_rank = level_rank(current_level)
    print(f"sync-autonomy: current level={current_level}")

    mismatches = []
    providers_dir = root / ".agent/providers"
    for mf in sorted(providers_dir.glob("*.json")):
        data = json.loads(mf.read_text())
        provider = data.get("provider", mf.stem)
        autonomy_cfg = data.get("autonomy", {})
        max_level = autonomy_cfg.get("max_honerable_level", "medium")
        supports_sync = autonomy_cfg.get("supports_policy_sync", False)

        if provider == "gemini-cli" and supports_sync:
            applied = sync_gemini_policy(root, current_rank)
            print(f"   ✓ gemini-cli: wrote {applied}-autonomy policy → .gemini/policies/autonomy.toml")
            # After sync, gemini-cli can honor any level we write for
            print(f"   OK gemini-cli: can honor {current_level} (synced)")
            continue

        if current_rank > level_rank(max_level):
            mismatches.append(provider)
            print(
                f"AUTONOMY MISMATCH: {provider} max_honerable_level={max_level},"
                f" current={current_level} (sync_mechanism={autonomy_cfg.get('sync_mechanism','none')})"
            )
        else:
            print(f"   OK {provider}: can honor {current_level} (max={max_level})")

    if mismatches:
        print(
            f"{len(mismatches)} provider(s) cannot honor autonomy={current_level}."
            " These providers have no sync_mechanism — limitation is inherent."
        )
    else:
        print(f"sync-autonomy complete -- all syncable providers honor {current_level}")


if __name__ == "__main__":
    main()
