// =============================================================
// SAOC — e2e/contact-form-mocked.spec.ts
// Mission ticketing-complete M1/F7 — HARD RULE (2026-09-08, team lead): POST
// /api/contact sends a real Resend email and writes a real Firestore
// `contactSubmissions` document. It is shared by TWO forms — ContactForm.tsx
// (/contact) and SuggestionForm.tsx (/members), discriminated only by a `subject`
// field. This is the ONLY spec file in this suite allowed to submit either form
// (see contract-f7.yaml A18, a repo-wide negative-grep banning any other spec from
// doing so).
//
// Mocked at the BROWSER network boundary (page.route + route.fulfill), never a
// server-side test-mode branch — both forms submit via client-side fetch(), which
// Playwright intercepts before the request ever leaves the browser context, so
// neither the Resend call nor the Firestore write ever happens. The unsafe
// polarity — letting the real request pass through unmocked — is never used (that
// would defeat the whole point).
// Each test sets a boolean flag INSIDE the route callback and asserts it true AFTER
// submission — proving the mock actually fired, not merely that a page.route() call
// exists that might never match (the same defect class as declared-but-never-
// imported code).
import { expect, test } from '@playwright/test';

test.describe('contact and suggestion forms — mocked, never a real send', () => {
  test('ContactForm (/contact) posts to a mocked /api/contact', async ({ page }) => {
    let interceptedContactRequest = false;

    await page.route('**/api/contact', async (route) => {
      interceptedContactRequest = true;
      await route.fulfill({
        status: 201,
        contentType: 'application/json',
        body: JSON.stringify({ ok: true }),
      });
    });

    await page.goto('/contact');
    // Both forms are Client Components ('use client'); their onSubmit handler
    // (which calls preventDefault before anything else) only exists once React
    // hydration completes. Filling/clicking too early risks the click landing on
    // the still-unhydrated, plain <button type="submit"> and triggering a native
    // form GET navigation instead of the mocked fetch. Waiting for the network to
    // go idle gives hydration time to finish first.
    await page.waitForLoadState('networkidle');

    await page.locator('#cf-name').fill('Playwright Test');
    await page.locator('#cf-email').fill('playwright-test@example.com');
    await page.locator('#cf-subject').fill('Automated harness check');
    await page
      .locator('#cf-message')
      .fill('This message is generated by the Playwright e2e harness and is mocked.');

    await page.getByRole('button', { name: 'Send message' }).click();

    await expect(page.getByText('Thank you')).toBeVisible();
    expect(interceptedContactRequest).toBe(true);
  });

  test('SuggestionForm (/members) posts to a mocked /api/contact', async ({ page }) => {
    let interceptedContactRequest = false;

    await page.route('**/api/contact', async (route) => {
      interceptedContactRequest = true;
      await route.fulfill({
        status: 201,
        contentType: 'application/json',
        body: JSON.stringify({ ok: true }),
      });
    });

    await page.goto('/members');
    await page.waitForLoadState('networkidle');

    await page.locator('#msf-name').fill('Playwright Test');
    await page.locator('#msf-email').fill('playwright-test@example.com');
    await page
      .locator('#msf-message')
      .fill('This suggestion is generated by the Playwright e2e harness and is mocked.');

    await page.getByRole('button', { name: 'Send suggestion' }).click();

    await expect(page.getByText('Thank you')).toBeVisible();
    expect(interceptedContactRequest).toBe(true);
  });
});
