import type { VendorRegisterFormState } from './vendor-register-form-payload';

// Extracted out of VendorRegisterForm.tsx to keep that component under this project's
// 150-line convention (see .claude/rules/coding.md) -- INITIAL_STATE is pure data, no JSX,
// so it carries no cost being in its own module.
export const INITIAL_STATE: VendorRegisterFormState = {
  businessName: '',
  tradingName: '',
  tradingNameSameAsBusiness: false,
  businessEntityType: '',
  businessEntityTypeOther: '',
  contactPersonName: '',
  contactPosition: '',
  contactCellPhone: '',
  alternativeContactNumber: '',
  contactEmail: '',
  accountsContactName: '',
  accountsContactEmail: '',
  physicalAddress: '',
  postalAddressSameAsPhysical: false,
  postalAddress: '',
  cipcNumber: '',
  vatRegistered: '',
  vatNumber: '',
  countryOfBusinessRegistration: '',
  website: '',
  emergencyContactName: '',
  emergencyContactRelationship: '',
  emergencyContactCellPhone: '',

  facebookHandle: '',
  instagramHandle: '',
  tiktokHandle: '',
  youtubeHandle: '',
  otherSocialMediaHandle: '',

  vendorCategory: [],
  vendorCategoryOther: '',
  productDescription: '',
  phytosanitaryPermitNumber: '',
  citesPermitNumber: '',
  foodHandlingCertificateNumber: '',
  foodItemList: '',
  citesListedSpecies: '',
  foodHealthTradingDocumentation: '',
  foodVendorCertifications: [],

  boothSize: '',
  boothType: '',
  boothPositionRequest: '',
  adjacentBoothRequested: '',
  adjacentBoothVendorName: '',
  specialDisplayRequirements: '',
  tableCount: '',
  chairCount: '',
  powerRequired: '',
  electricalOutletsRequired: '',
  electricalEquipmentEntries: [],
  gasEquipmentEntries: [],

  waterRequired: '',
  waterIntendedUse: '',
  wastewaterDrainageRequired: '',
  wastewaterDrainageDetails: '',
  staffPerDay: '',

  carRegistrationNumber: '',
  suvBakkieRegistrationNumber: '',
  panelVanRegistrationNumber: '',
  deliveryVanRegistrationNumber: '',
  truckRegistrationNumber: '',
  trailerRegistrationNumber: '',
  otherVehicleRegistrationNumber: '',
  otherVehicleDescription: '',

  loadInSlot: '',
  loadOutSlot: '',
  bio: '',

  marketingPermission: '',

  publicLiabilityInsurancePolicyNumber: '',
  productLiabilityInsurancePolicyNumber: '',

  paymentMethodsAccepted: [],
  paymentReference: '',
  termsAccepted: false,

  signatureFullName: '',
};
