#!/usr/bin/env bash
# A16 — the footer's Lapis-monotone (E4) emblem is generated by reproducing
# app.js's own duotone mapping exactly (.tmp/sandbox/council-artifact/app.js,
# the LAPIS constant at line 3 and variant()'s e===3 branch at lines 68-86,
# specifically the lo/hi colours at lines 76-77 and the per-pixel loop at
# lines 78-83) — not a hand-tuned recolour. A hand-tuned version would not,
# by chance, reproduce these exact constants: lo = #1f3a93 (LAPIS), hi =
# #eef1fa, luminance weights 0.3/0.59/0.11, and the 1.35/-0.2 contrast
# stretch. Checked at the source level (the only robust way to prove "not
# hand-tuned" without assuming a specific resize algorithm — see the golden's
# Addendum 1 for why a post-resize pixel comparison would be flaky instead).
set -euo pipefail

SCRIPT="scripts/generate-saoc-emblem-web-assets.py"

if [ ! -f "$SCRIPT" ]; then
  echo "missing: $SCRIPT"
  exit 1
fi

FAIL=0
grep -qi "1f3a93" "$SCRIPT" || { echo "missing LAPIS lo-colour #1f3a93 (app.js:3,76)"; FAIL=1; }
grep -qi "eef1fa" "$SCRIPT" || { echo "missing hi-colour #eef1fa (app.js:77)"; FAIL=1; }
grep -qE "0\.3[^0-9]|0\.59|0\.11" "$SCRIPT" || { echo "missing luminance weights 0.3/0.59/0.11 (app.js:80)"; FAIL=1; }
grep -qE "1\.35" "$SCRIPT" || { echo "missing contrast-stretch factor 1.35 (app.js:81)"; FAIL=1; }

if [ "$FAIL" -ne 0 ]; then
  exit 1
fi

echo "OK: $SCRIPT reproduces app.js's Lapis-monotone duotone formula (LAPIS/eef1fa, 0.3/0.59/0.11, 1.35/-0.2)"
