/**
 * SAOC LLM Content Refresh Script
 *
 * Crawls each public page through the Alembic distilling proxy and assembles
 * the clean Markdown output into public/llms-full.txt.
 *
 * Run with: pnpm refresh-llms
 *
 * Optional env:
 *   REFRESH_BASE_URL — base URL of the running Next dev server (default: http://localhost:3001)
 *
 * Requires both the Next dev server and the Alembic proxy (http://localhost:7077) to be up.
 */

import { execSync } from 'node:child_process';
import { writeFileSync } from 'node:fs';
import { join } from 'node:path';

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

interface Page {
  path: string;
  title: string;
}

const PAGES: Page[] = [
  { path: '/', title: 'Home' },
  { path: '/about', title: 'About' },
  { path: '/societies', title: 'Societies' },
  { path: '/judging', title: 'Judging' },
  { path: '/events', title: 'Events' },
  { path: '/national-show', title: 'National Show' },
  { path: '/contact', title: 'Contact' },
];

const BASE_URL = process.env.REFRESH_BASE_URL ?? 'http://localhost:3001';
const ALEMBIC = 'http://localhost:7077';
const OUTPUT_PATH = join(process.cwd(), 'public', 'llms-full.txt');

// ---------------------------------------------------------------------------
// Crawl helpers
// ---------------------------------------------------------------------------

function fetchPage(path: string): string {
  const url = `${ALEMBIC}/${BASE_URL}${path}`;
  try {
    return execSync(`curl -s "${url}"`, { encoding: 'utf8', timeout: 10000 });
  } catch {
    return '';
  }
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

function main(): void {
  const timestamp = new Date().toISOString();

  const header = [
    '# South African Orchid Council — Full Site Content',
    '',
    'Source: SAOC website (saoc.co.za) — auto-generated by scripts/refresh-llms.ts',
    `Last updated: ${timestamp}`,
  ].join('\n');

  const sections: string[] = [];

  for (const { path, title } of PAGES) {
    process.stderr.write(`→ fetching ${path}\n`);
    const body = fetchPage(path).trim();
    if (!body) {
      process.stderr.write(`  ⚠ warning: empty response for ${path}\n`);
    }
    sections.push(`## ${title}\n\n${body}`);
  }

  const footer = [
    '---',
    '## Scope Boundary',
    'SAOC covers orchids in cultivation: growing, showing, hybridising, judging, community.',
    'Wild orchid conservation and identification → WOSA (Wild Orchids of Southern Africa): wosa.org.za',
  ].join('\n');

  const content = [header, ...sections, footer].join('\n\n');
  writeFileSync(OUTPUT_PATH, content, 'utf8');
  process.stderr.write(`✓ written ${OUTPUT_PATH}\n`);
}

main();
